# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bicicleta.proto for package 'paraibike'

require 'grpc'
require 'bicicleta'

module Paraibike
  module BicicletaService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'paraibike.BicicletaService'

      rpc :findBicicleta, ::Paraibike::Bicicleta, ::Paraibike::Bicicleta
      rpc :listBicicletas, ::Paraibike::NoContent, ::Paraibike::Bicicletas
      rpc :listBicicletasByLocador, ::Paraibike::Usuario, ::Paraibike::Bicicletas
      rpc :createBicicleta, ::Paraibike::Bicicleta, ::Paraibike::Bicicleta
      rpc :updateBicicleta, ::Paraibike::Bicicleta, ::Paraibike::Bicicleta
      rpc :inactivateBicicleta, ::Paraibike::Bicicleta, ::Paraibike::Feedback
    end

    Stub = Service.rpc_stub_class
  end
  module AluguelService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'paraibike.AluguelService'

      rpc :findAluguel, ::Paraibike::Aluguel, ::Paraibike::Aluguel
      rpc :listAlugueis, ::Paraibike::NoContent, ::Paraibike::Alugueis
      rpc :createAluguel, ::Paraibike::Aluguel, ::Paraibike::Aluguel
      rpc :updateAluguel, ::Paraibike::Aluguel, ::Paraibike::Aluguel
      rpc :deleteAluguel, ::Paraibike::Aluguel, ::Paraibike::Feedback
    end

    Stub = Service.rpc_stub_class
  end
end
