# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bicicleta.proto

require 'google/protobuf'


descriptor_data = "\n\x0f\x62icicleta.proto\x12\tparaibike\"Y\n\tBicicleta\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x63odigo\x18\x02 \x01(\t\x12\r\n\x05marca\x18\x03 \x01(\t\x12\x0e\n\x06\x65stado\x18\x04 \x01(\t\x12\x11\n\tusuarioId\x18\x05 \x01(\x05\"\x15\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x05\"6\n\nBicicletas\x12(\n\nbicicletas\x18\x01 \x03(\x0b\x32\x14.paraibike.Bicicleta\"~\n\x07\x41luguel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x11\n\tusuarioId\x18\x05 \x01(\x05\x12\'\n\tbicicleta\x18\x06 \x01(\x0b\x32\x14.paraibike.Bicicleta\"/\n\x08\x41lugueis\x12#\n\x07\x61luguel\x18\x01 \x03(\x0b\x32\x12.paraibike.Aluguel\"\x0b\n\tNoContent\"\x1b\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9c\x03\n\x10\x42icicletaService\x12=\n\rfindBicicleta\x12\x14.paraibike.Bicicleta\x1a\x14.paraibike.Bicicleta\"\x00\x12?\n\x0elistBicicletas\x12\x14.paraibike.NoContent\x1a\x15.paraibike.Bicicletas\"\x00\x12\x46\n\x17listBicicletasByLocador\x12\x12.paraibike.Usuario\x1a\x15.paraibike.Bicicletas\"\x00\x12?\n\x0f\x63reateBicicleta\x12\x14.paraibike.Bicicleta\x1a\x14.paraibike.Bicicleta\"\x00\x12?\n\x0fupdateBicicleta\x12\x14.paraibike.Bicicleta\x1a\x14.paraibike.Bicicleta\"\x00\x12>\n\x0f\x64\x65leteBicicleta\x12\x14.paraibike.Bicicleta\x1a\x13.paraibike.Feedback\"\x00\x32\xb8\x02\n\x0e\x41luguelService\x12\x37\n\x0b\x66indAluguel\x12\x12.paraibike.Aluguel\x1a\x12.paraibike.Aluguel\"\x00\x12;\n\x0clistAlugueis\x12\x14.paraibike.NoContent\x1a\x13.paraibike.Alugueis\"\x00\x12\x39\n\rcreateAluguel\x12\x12.paraibike.Aluguel\x1a\x12.paraibike.Aluguel\"\x00\x12\x39\n\rupdateAluguel\x12\x12.paraibike.Aluguel\x1a\x12.paraibike.Aluguel\"\x00\x12:\n\rdeleteAluguel\x12\x12.paraibike.Aluguel\x1a\x13.paraibike.Feedback\"\x00\x42\x1f\n\x1b\x62r.com.paraibike.protofilesP\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Paraibike
  Bicicleta = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("paraibike.Bicicleta").msgclass
  Usuario = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("paraibike.Usuario").msgclass
  Bicicletas = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("paraibike.Bicicletas").msgclass
  Aluguel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("paraibike.Aluguel").msgclass
  Alugueis = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("paraibike.Alugueis").msgclass
  NoContent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("paraibike.NoContent").msgclass
  Feedback = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("paraibike.Feedback").msgclass
end
