# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bicicleta.proto for package 'paraibike'

require 'grpc'
require 'bicicleta_pb'

module Paraibike
  module BicicletaService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'paraibike.BicicletaService'

      rpc :find_bicicleta, ::Paraibike::Bicicleta, ::Paraibike::Bicicleta
      rpc :list_bicicletas, ::Paraibike::NoContent, ::Paraibike::Bicicletas
      rpc :list_bicicletas_by_locador, ::Paraibike::Usuario, ::Paraibike::Bicicletas
      rpc :create_bicicleta, ::Paraibike::Bicicleta, ::Paraibike::Bicicleta
      rpc :update_bicicleta, ::Paraibike::Bicicleta, ::Paraibike::Bicicleta
      rpc :inactivate_bicicleta, ::Paraibike::Bicicleta, ::Paraibike::Feedback
    end

    Stub = Service.rpc_stub_class
  end
  module AluguelService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'paraibike.AluguelService'

      rpc :find_aluguel, ::Paraibike::Aluguel, ::Paraibike::Aluguel
      rpc :list_alugueis, ::Paraibike::NoContent, ::Paraibike::Alugueis
      rpc :create_aluguel, ::Paraibike::Aluguel, ::Paraibike::Aluguel
      rpc :update_aluguel, ::Paraibike::Aluguel, ::Paraibike::Aluguel
      rpc :cancel_aluguel, ::Paraibike::Aluguel, ::Paraibike::Feedback
    end

    Stub = Service.rpc_stub_class
  end
end
